# Generated by Django 5.2.6 on 2025-10-15 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_make_service_address_nullable'),
        ('locations', '0002_alter_address_latitude_alter_address_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee ID', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('specialization', models.CharField(choices=[('general', 'General Mechanic'), ('car_specialist', 'Car Specialist'), ('bike_specialist', 'Bike Specialist'), ('electrician', 'Auto Electrician'), ('painter', 'Auto Painter')], default='general', max_length=30)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current GPS latitude', max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current GPS longitude', max_digits=9, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Currently available for jobs')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verification_documents', models.JSONField(default=dict, help_text='Stored document URLs and metadata')),
                ('background_check_completed', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_areas', models.ManyToManyField(help_text='Service areas this provider covers', related_name='providers', to='locations.servicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Provider'), ('accepted', 'Accepted by Provider'), ('rejected', 'Rejected by Provider'), ('en_route', 'Provider En Route'), ('in_progress', 'Service In Progress'), ('completed', 'Service Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_time', models.DateTimeField(blank=True, null=True)),
                ('provider_notes', models.TextField(blank=True, help_text="Provider's notes about the job")),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='bookings.booking')),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='service_providers.serviceprovider')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['verification_status'], name='service_pro_verific_62f208_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_available'], name='service_pro_is_avai_463bba_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='service_pro_current_85713e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignment',
            index=models.Index(fields=['status'], name='service_pro_status_455a46_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignment',
            index=models.Index(fields=['booking'], name='service_pro_booking_3226d1_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignment',
            index=models.Index(fields=['service_provider', 'status'], name='service_pro_service_8255f3_idx'),
        ),
    ]
