# Generated by Django 5.2.6 on 2025-10-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_type_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_mobile__16709d_idx',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_mobile__7d0fd3_idx',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='otp_code',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
