# Generated by Django 5.2.6 on 2025-10-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_user_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='accounts_ot_mobile__16709d_idx',
            old_name='accounts_ot_mobile__idx',
        ),
        migrations.RenameIndex(
            model_name='otp',
            new_name='accounts_ot_mobile__7d0fd3_idx',
            old_name='accounts_ot_mobile__verified_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_mobile__bd5794_idx',
            old_name='accounts_us_mobile__idx',
        ),
    ]
