# Generated by Django 5.2.6 on 2025-10-15 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('locations', '0002_alter_address_latitude_alter_address_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_user_id_4a9385_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_status_72dd85_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_latitud_93164c_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_address',
        ),
        migrations.AddField(
            model_name='booking',
            name='location_name',
            field=models.CharField(blank=True, help_text='Human-readable location name', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='locations.address'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='bookings_bo_user_id_6151bb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
