# Generated by Django 5.2.6 on 2025-10-15 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_bookings_bo_user_id_4a9385_idx_and_more'),
        ('locations', '0002_alter_address_latitude_alter_address_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_user_id_6151bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_status_233e96_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_address',
            field=models.TextField(blank=True, help_text='Full address text for service location', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, help_text="Reference to user's saved address (if used)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'date'], name='bookings_bo_user_id_4a9385_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['latitude', 'longitude'], name='bookings_bo_latitud_93164c_idx'),
        ),
    ]
