# Generated by Django 5.2.6 on 2025-10-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_booking_indexes_and_meta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_user_id_4a9385_idx',
            old_name='bookings_bo_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_status_72dd85_idx',
            old_name='bookings_bo_status_created_idx',
        ),
    ]
