# Generated by Django 5.2.6 on 2025-10-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_location_fields'),
        ('bookings', '0004_rename_bookings_bo_user_id_date_idx_bookings_bo_user_id_4a9385_idx_and_more'),
    ]

    operations = [
    ]
