# Generated by Django 5.2.6 on 2025-10-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_merge_20251011_1756'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_latitud_93164c_idx',
            old_name='bookings_bo_latitud_idx',
        ),
    ]
